<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <PropertyGroup>
    <XHKWinMDPath>$(MSBuildThisFileDirectory)..\..\lib\uap10.0\XamlHostingKit.winmd</XHKWinMDPath>
    <XHKWinMDImplementationDllName>XamlHostingKit.dll</XHKWinMDImplementationDllName>
  </PropertyGroup>

  <PropertyGroup>
    <XHKPlatform Condition="$(RuntimeIdentifier.EndsWith('-x64'))">x64</XHKPlatform>
    <XHKPlatform Condition="$(RuntimeIdentifier.EndsWith('-x86'))">x86</XHKPlatform>
    <XHKPlatform Condition="$(RuntimeIdentifier.EndsWith('-arm64'))">arm64</XHKPlatform>
    <XHKPlatform Condition="$(RuntimeIdentifier.EndsWith('-arm'))">arm</XHKPlatform>
  </PropertyGroup>

  <PropertyGroup Condition="'$(XHKPlatform)' == ''">
    <XHKPlatform Condition="'$(Platform)' == 'Win32'">x86</XHKPlatform>
    <XHKPlatform Condition="'$(Platform)' != 'Win32'">$(Platform)</XHKPlatform>
    <XHKPlatform Condition="'$(Platform)' == 'AnyCPU'"></XHKPlatform>
  </PropertyGroup>

  <PropertyGroup>
    <XHKWarnNoPlatform Condition="'$(XHKWarnNoPlatform)' == ''">true</XHKWarnNoPlatform>
  </PropertyGroup>

  <ItemGroup>
    <WindowsMetadataReference Include="$(XHKWinMDPath)" Implementation="$(XHKWinMDImplementationDllName)" />
  </ItemGroup>

  <Target Name="XHKWarnNoPlatform" BeforeTargets="BeforeBuild" Condition="'$(XHKPlatform)' == '' and '$(XHKWarnNoPlatform)' == 'true'">
    <Warning
        Code="XHK0001"
        Text="'XamlHostingKit.dll' cannot be referenced correctly, because the project is being built as 'AnyCPU'. Please specify a specific platform (eg. 'x64'), publish with a RID (runtime identifier, eg. 'win-x64'), or set 'XHKWarnNoPlatform' to suppress this error (note: you'll need to manually handle referencing XamlHostingKit.dll in that case)." />
  </Target>

</Project>
