<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <PropertyGroup>
    <XHKLinkDetours Condition="'$(XHKLinkDetours)' == ''">true</XHKLinkDetours>
    <XHKPlatform Condition="'$(Platform)' == 'Win32' and '$(XHKPlatform)' == ''">x86</XHKPlatform>
    <XHKPlatform Condition="'$(Platform)' != 'Win32' and '$(XHKPlatform)' == ''">$(Platform)</XHKPlatform>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="$(MSBuildThisFileDirectory)..\..\lib\native\XamlHostingKit.winmd" />
  </ItemGroup>

  <ItemDefinitionGroup>
    <ClCompile>
      <AdditionalIncludeDirectories>%(AdditionalIncludeDirectories);$(MSBuildThisFileDirectory)..\..\include</AdditionalIncludeDirectories>
    </ClCompile>
    <Link>
      <AdditionalLibraryDirectories>%(AdditionalLibraryDirectories);$(MSBuildThisFileDirectory)..\..\lib\native\$(XHKPlatform)</AdditionalLibraryDirectories>
      <AdditionalDependencies>%(AdditionalDependencies);XamlHostingKit.Static.lib;Urlmon.lib;Shcore.lib;dwmapi.lib;shlwapi.lib;ntdll.lib;user32.lib;shell32.lib</AdditionalDependencies>
      <AdditionalDependencies Condition="'$(XHKLinkDetours)' == 'true'">%(AdditionalDependencies);$(MSBuildThisFileDirectory)..\..\lib\native\$(XHKPlatform)\external\Detours.lib</AdditionalDependencies>
      <AdditionalOptions>%(AdditionalOptions) /LTCG</AdditionalOptions>
    </Link>
  </ItemDefinitionGroup>

</Project>