<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <PropertyGroup>
    <XHKPlatform Condition="'$(Platform)' == 'Win32'">x86</XHKPlatform>
    <XHKPlatform Condition="'$(Platform)' != 'Win32'">$(Platform)</XHKPlatform>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="$(MSBuildThisFileDirectory)..\..\lib\native\XamlHostingKit.winmd" />
  </ItemGroup>

  <ItemDefinitionGroup>
    <!--ClCompile>
      <AdditionalIncludeDirectories>$(MSBuildThisFileDirectory)..\..\include;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
    </ClCompile-->
    <Link>
      <AdditionalLibraryDirectories>%(AdditionalLibraryDirectories);$(MSBuildThisFileDirectory)..\..\runtimes\win-$(XHKPlatform)\native</AdditionalLibraryDirectories>
      <AdditionalDependencies>%(AdditionalDependencies);XamlHostingKit.Static.lib</AdditionalDependencies>
    </Link>
  </ItemDefinitionGroup>

</Project>