<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.10240.0</TargetPlatformMinVersion>
    <Nullable>enable</Nullable>
    <UseUwp>true</UseUwp>
    <UseUwpTools>false</UseUwpTools>
    <DefaultLanguage>en-US</DefaultLanguage>
    <IsAotCompatible>true</IsAotCompatible>
    <DisableRuntimeMarshalling>true</DisableRuntimeMarshalling>
    <CsWinRTIncludes>XamlHostingKit</CsWinRTIncludes>
    <ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>None</ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.CsWinRT" Version="2.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\XamlHostingKit\XamlHostingKit.vcxproj" />
    <ProjectReference Include="..\XamlHostingKit.Static\XamlHostingKit.Static.vcxproj" PrivateAssets="all" />
  </ItemGroup>

</Project>