<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <WindowsSdkPackageVersion>10.0.26100.87</WindowsSdkPackageVersion>
    <TargetPlatformVersion>10.0.26100.0</TargetPlatformVersion>
    <TargetPlatformMinVersion>10.0.14393.0</TargetPlatformMinVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishAot>true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
    <DisableRuntimeMarshalling>true</DisableRuntimeMarshalling>
    <UseUwp>true</UseUwp>
    <UseUwpTools>true</UseUwpTools>
    <DefineConstants>DISABLE_XAML_GENERATED_MAIN;$(DefineConstants)</DefineConstants>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Platforms>x64;arm64;x86</Platforms>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <PublishProfile>win-$(Platform).pubxml</PublishProfile>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <DisableEmbeddedXbf>false</DisableEmbeddedXbf>
    <EnableMsixTooling>true</EnableMsixTooling>
    <ProjectPriFileName>resources.pri</ProjectPriFileName>
    <_SupportEmbedFileResources>true</_SupportEmbedFileResources>
    <CsWinRTAotWarningLevel>3</CsWinRTAotWarningLevel>
    <LangVersion>preview</LangVersion>
    <CsWinRTIIDOptimizerOptOut>true</CsWinRTIIDOptimizerOptOut>
    <SkipXamlDesignerSdkCheck>true</SkipXamlDesignerSdkCheck>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Images\COMplicated.png" />
    <None Remove="Test.html" />
  </ItemGroup>

  <ItemGroup>
    <AppxTargetDeviceFamilyItem Include="Windows.Desktop" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Images\COMplicated.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Test.html">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.CsWinRT" Version="2.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\XamlHostingKit.Projection\XamlHostingKit.Projection.csproj" />
  </ItemGroup>

</Project>
